#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=96:00:00
#PBS -l pmem=1gb                ## Requests 1 gigabytes of memory per process
#PBS -A ebf11_a_g_sc_default 	## Specifies the allocation. Use –A open for open queue
#PBS -j oe                      ## Requests that regular output and terminal output go to the same file
cd $PBS_O_WORKDIR
module load python/3.3.2
export PATH="/storage/work/ajs725/conda/install/bin:$PATH"
source activate stability
