#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=96:00:00
#PBS -l pmem=1gb
#PBS -A cyberlamp
#PBS -j oe         
cd $PBS_O_WORKDIR
export PATH="/storage/work/ajs725/conda/install/bin:$PATH"
source activate stability3.5.2
