#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=20:00:00
#PBS -l pmem=1gb
#PBS -A ebf11_a_g_sc_default
#PBS -j oe                      
cd $PBS_O_WORKDIR
export PATH="/storage/work/ajs725/conda/install/bin:$PATH"
source activate stability3.5.2
